/**
 * 成就徽章定义种子脚本
 *
 * 用法: npx ts-node prisma/seed-badges.ts
 * 或通过 admin API POST /admin/badges/seed 触发
 *
 * 使用 upsert 确保幂等，可重复执行。
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface BadgeSeed {
  key: string;
  title: string;
  description: string;
  emoji: string;
  category: string;
  ownerType: string;
  triggerType: string;
  evaluatorType: string;
  evaluatorConfig: Record<string, unknown>;
  hidden: boolean;
  progressTarget: number | null;
  sortOrder: number;
}

export const BADGES: BadgeSeed[] = [
  // ========================================================================
  // A. 厨师之路 (11)
  // ========================================================================
  {
    key: 'chef_first_dish',
    title: '厨师初体验',
    description: '做出人生第一道菜',
    emoji: '👨‍🍳',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'chefUserId',
      threshold: 1,
    },
    hidden: false,
    progressTarget: 1,
    sortOrder: 100,
  },
  {
    key: 'chef_10_dishes',
    title: '厨师小学徒',
    description: '累计做 10 道菜',
    emoji: '🥘',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'chefUserId',
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 110,
  },
  {
    key: 'chef_50_dishes',
    title: '厨师小当家',
    description: '累计做 50 道菜',
    emoji: '🍳',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'chefUserId',
      threshold: 50,
    },
    hidden: false,
    progressTarget: 50,
    sortOrder: 120,
  },
  {
    key: 'chef_100_dishes',
    title: '厨师大师傅',
    description: '累计做 100 道菜',
    emoji: '🎖️',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'chefUserId',
      threshold: 100,
    },
    hidden: false,
    progressTarget: 100,
    sortOrder: 130,
  },
  {
    key: 'chef_365_dishes',
    title: '传说厨神',
    description: '累计做 365 道菜',
    emoji: '👑',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'chefUserId',
      threshold: 365,
    },
    hidden: false,
    progressTarget: 365,
    sortOrder: 140,
  },
  {
    key: 'five_star_streak_3',
    title: '三星好评',
    description: '连续 3 次获得五星',
    emoji: '✨',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'streak',
    evaluatorConfig: { model: 'order', scopeBy: 'chefUserId', check: 'stars===5', length: 3 },
    hidden: false,
    progressTarget: 3,
    sortOrder: 150,
  },
  {
    key: 'five_star_streak_5',
    title: '五星连击',
    description: '连续 5 次获得五星',
    emoji: '⭐',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'streak',
    evaluatorConfig: { model: 'order', scopeBy: 'chefUserId', check: 'stars===5', length: 5 },
    hidden: false,
    progressTarget: 5,
    sortOrder: 160,
  },
  {
    key: 'five_star_streak_10',
    title: '十全十美',
    description: '连续 10 次获得五星',
    emoji: '💫',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'streak',
    evaluatorConfig: { model: 'order', scopeBy: 'chefUserId', check: 'stars===5', length: 10 },
    hidden: false,
    progressTarget: 10,
    sortOrder: 170,
  },
  {
    key: 'chef_midnight',
    title: '深夜食堂',
    description: '深夜 23:00-5:00 间上菜',
    emoji: '🌙',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_served',
    evaluatorType: 'time_check',
    evaluatorConfig: { field: 'servedAt', hourRange: { start: 23, end: 5 } },
    hidden: false,
    progressTarget: null,
    sortOrder: 180,
  },
  {
    key: 'chef_speed',
    title: '闪电大厨',
    description: '接单 30 分钟内上菜',
    emoji: '⚡',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_served',
    evaluatorType: 'time_check',
    evaluatorConfig: { field: 'servedAt', withinMinutesFrom: 'acceptedAt', maxMinutes: 30 },
    hidden: false,
    progressTarget: null,
    sortOrder: 190,
  },
  {
    key: 'chef_hard_3',
    title: '迎难而上',
    description: '完成 3 道最高难度菜',
    emoji: '💪',
    category: 'chef',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'chefUserId',
      itemFilter: { recipeDifficulty: 5 },
      threshold: 3,
    },
    hidden: false,
    progressTarget: 3,
    sortOrder: 200,
  },

  // ========================================================================
  // B. 吃货之路 (8)
  // ========================================================================
  {
    key: 'customer_first_order',
    title: '第一个点单',
    description: '下出你的第一单',
    emoji: '📋',
    category: 'customer',
    ownerType: 'user',
    triggerType: 'order_created',
    evaluatorType: 'count',
    evaluatorConfig: { model: 'order', scopeBy: 'customerUserId', threshold: 1 },
    hidden: false,
    progressTarget: 1,
    sortOrder: 300,
  },
  {
    key: 'customer_10_orders',
    title: '资深吃货',
    description: '累计点餐 10 次',
    emoji: '🍴',
    category: 'customer',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'customerUserId',
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 310,
  },
  {
    key: 'customer_50_orders',
    title: '美食鉴赏家',
    description: '累计点餐 50 次',
    emoji: '🧐',
    category: 'customer',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'customerUserId',
      threshold: 50,
    },
    hidden: false,
    progressTarget: 50,
    sortOrder: 320,
  },
  {
    key: 'customer_100_orders',
    title: '吃货之王',
    description: '累计点餐 100 次',
    emoji: '👑',
    category: 'customer',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'customerUserId',
      threshold: 100,
    },
    hidden: false,
    progressTarget: 100,
    sortOrder: 330,
  },
  {
    key: 'rater_first_comment',
    title: '第一句点评',
    description: '写下第一条评价',
    emoji: '💬',
    category: 'customer',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'first_time',
    evaluatorConfig: {
      model: 'rating',
      scopeBy: 'raterUserId',
      filters: { comment: { not: null } },
    },
    hidden: false,
    progressTarget: null,
    sortOrder: 340,
  },
  {
    key: 'rater_10_five_stars',
    title: '完美主义',
    description: '给了 10 次五星',
    emoji: '💯',
    category: 'customer',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'rating',
      scopeBy: 'raterUserId',
      filters: { stars: 5 },
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 350,
  },
  {
    key: 'rater_20_comments',
    title: '美食评论家',
    description: '写了 20 条评价评论',
    emoji: '✍️',
    category: 'customer',
    ownerType: 'user',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'rating',
      scopeBy: 'raterUserId',
      filters: { comment: { not: null } },
      threshold: 20,
    },
    hidden: false,
    progressTarget: 20,
    sortOrder: 360,
  },
  {
    key: 'customer_rush_10',
    title: '催菜达人',
    description: '催菜累计 10 次',
    emoji: '🔔',
    category: 'customer',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'orderMessage',
      scopeBy: 'senderUserId',
      filters: { type: 'rush' },
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 370,
  },

  // ========================================================================
  // C. 菜谱收藏 (9)
  // ========================================================================
  {
    key: 'recipe_first_create',
    title: '第一道菜谱',
    description: '创建了第一道菜谱',
    emoji: '📝',
    category: 'recipe',
    ownerType: 'user',
    triggerType: 'recipe_created',
    evaluatorType: 'count',
    evaluatorConfig: { model: 'recipe', scopeBy: 'createdByUserId', threshold: 1 },
    hidden: false,
    progressTarget: 1,
    sortOrder: 500,
  },
  {
    key: 'recipe_5_created',
    title: '小小菜谱本',
    description: '创建了 5 道菜谱',
    emoji: '📖',
    category: 'recipe',
    ownerType: 'user',
    triggerType: 'recipe_created',
    evaluatorType: 'count',
    evaluatorConfig: { model: 'recipe', scopeBy: 'createdByUserId', threshold: 5 },
    hidden: false,
    progressTarget: 5,
    sortOrder: 510,
  },
  {
    key: 'recipe_10_created',
    title: '家传菜谱',
    description: '创建了 10 道菜谱',
    emoji: '📚',
    category: 'recipe',
    ownerType: 'user',
    triggerType: 'recipe_created',
    evaluatorType: 'count',
    evaluatorConfig: { model: 'recipe', scopeBy: 'createdByUserId', threshold: 10 },
    hidden: false,
    progressTarget: 10,
    sortOrder: 520,
  },
  {
    key: 'recipe_20_created',
    title: '菜谱大师',
    description: '创建了 20 道菜谱',
    emoji: '🏅',
    category: 'recipe',
    ownerType: 'user',
    triggerType: 'recipe_created',
    evaluatorType: 'count',
    evaluatorConfig: { model: 'recipe', scopeBy: 'createdByUserId', threshold: 20 },
    hidden: false,
    progressTarget: 20,
    sortOrder: 530,
  },
  {
    key: 'recipe_first_favorite',
    title: '首次收藏',
    description: '收藏了第一道菜谱',
    emoji: '❤️',
    category: 'recipe',
    ownerType: 'user',
    triggerType: 'recipe_favorited',
    evaluatorType: 'count',
    evaluatorConfig: { model: 'recipeFavorite', scopeBy: 'userId', threshold: 1 },
    hidden: false,
    progressTarget: 1,
    sortOrder: 540,
  },
  {
    key: 'recipe_5_favorites',
    title: '精选收藏',
    description: '收藏了 5 道菜谱',
    emoji: '💎',
    category: 'recipe',
    ownerType: 'user',
    triggerType: 'recipe_favorited',
    evaluatorType: 'count',
    evaluatorConfig: { model: 'recipeFavorite', scopeBy: 'userId', threshold: 5 },
    hidden: false,
    progressTarget: 5,
    sortOrder: 550,
  },
  {
    key: 'recipe_popular_5',
    title: '人气菜品',
    description: '一道菜被点了 5 次',
    emoji: '🔥',
    category: 'recipe',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'recipe_stat',
    evaluatorConfig: { statField: 'orderCount', threshold: 5 },
    hidden: false,
    progressTarget: null,
    sortOrder: 560,
  },
  {
    key: 'recipe_popular_20',
    title: '招牌菜',
    description: '一道菜被点了 20 次',
    emoji: '🌟',
    category: 'recipe',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'recipe_stat',
    evaluatorConfig: { statField: 'orderCount', threshold: 20 },
    hidden: false,
    progressTarget: null,
    sortOrder: 570,
  },
  {
    key: 'recipe_perfect_rating',
    title: '满分菜谱',
    description: '一道菜均分 5.0',
    emoji: '🏆',
    category: 'recipe',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'recipe_stat',
    evaluatorConfig: { statField: 'avgRating', threshold: 5.0, minOrderCount: 3 },
    hidden: false,
    progressTarget: null,
    sortOrder: 580,
  },

  // ========================================================================
  // D. 爱心温暖 (7)
  // ========================================================================
  {
    key: 'love_first_earn',
    title: '第一颗爱心',
    description: '获得了第一颗爱心值',
    emoji: '💕',
    category: 'love',
    ownerType: 'user',
    triggerType: 'love_point_earned',
    evaluatorType: 'first_time',
    evaluatorConfig: {
      model: 'lovePointLog',
      scopeBy: 'userId',
      filters: { changeAmount: { gt: 0 }, changeType: 'cook_reward' },
    },
    hidden: false,
    progressTarget: null,
    sortOrder: 700,
  },
  {
    key: 'love_total_100',
    title: '爱心满满',
    description: '累计获得 100 爱心值',
    emoji: '💌',
    category: 'love',
    ownerType: 'user',
    triggerType: 'love_point_earned',
    evaluatorType: 'sum',
    evaluatorConfig: {
      model: 'lovePointLog',
      scopeBy: 'userId',
      filters: { changeAmount: { gt: 0 } },
      sumField: 'changeAmount',
      threshold: 100,
    },
    hidden: false,
    progressTarget: 100,
    sortOrder: 710,
  },
  {
    key: 'love_total_500',
    title: '爱心银行',
    description: '累计获得 500 爱心值',
    emoji: '🏦',
    category: 'love',
    ownerType: 'user',
    triggerType: 'love_point_earned',
    evaluatorType: 'sum',
    evaluatorConfig: {
      model: 'lovePointLog',
      scopeBy: 'userId',
      filters: { changeAmount: { gt: 0 } },
      sumField: 'changeAmount',
      threshold: 500,
    },
    hidden: false,
    progressTarget: 500,
    sortOrder: 720,
  },
  {
    key: 'love_total_2000',
    title: '爱心大亨',
    description: '累计获得 2000 爱心值',
    emoji: '💰',
    category: 'love',
    ownerType: 'user',
    triggerType: 'love_point_earned',
    evaluatorType: 'sum',
    evaluatorConfig: {
      model: 'lovePointLog',
      scopeBy: 'userId',
      filters: { changeAmount: { gt: 0 } },
      sumField: 'changeAmount',
      threshold: 2000,
    },
    hidden: false,
    progressTarget: 2000,
    sortOrder: 730,
  },
  {
    key: 'love_first_tip',
    title: '打赏新人',
    description: '第一次给对方打赏',
    emoji: '🎁',
    category: 'love',
    ownerType: 'user',
    triggerType: 'tip_settled',
    evaluatorType: 'first_time',
    evaluatorConfig: {
      model: 'lovePointLog',
      scopeBy: 'userId',
      filters: { changeType: 'tip_send' },
    },
    hidden: false,
    progressTarget: null,
    sortOrder: 740,
  },
  {
    key: 'love_tip_10',
    title: '慷慨解囊',
    description: '累计打赏 10 次',
    emoji: '🌹',
    category: 'love',
    ownerType: 'user',
    triggerType: 'tip_settled',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'lovePointLog',
      scopeBy: 'userId',
      filters: { changeType: 'tip_send' },
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 750,
  },
  {
    key: 'love_tip_received_10',
    title: '甜在心头',
    description: '累计收到 10 次打赏',
    emoji: '🍬',
    category: 'love',
    ownerType: 'user',
    triggerType: 'tip_settled',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'lovePointLog',
      scopeBy: 'userId',
      filters: { changeType: 'tip_receive' },
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 760,
  },

  // ========================================================================
  // E. 甜蜜互动 (8)
  // ========================================================================
  {
    key: 'msg_first_emoji',
    title: '第一次互动',
    description: '发送了第一个表情',
    emoji: '😘',
    category: 'interaction',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'first_time',
    evaluatorConfig: { model: 'orderMessage', scopeBy: 'senderUserId', filters: { type: 'emoji' } },
    hidden: false,
    progressTarget: null,
    sortOrder: 900,
  },
  {
    key: 'msg_first_image',
    title: '第一张照片',
    description: '发送了第一张图片',
    emoji: '📸',
    category: 'interaction',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'first_time',
    evaluatorConfig: { model: 'orderMessage', scopeBy: 'senderUserId', filters: { type: 'image' } },
    hidden: false,
    progressTarget: null,
    sortOrder: 910,
  },
  {
    key: 'msg_first_rush',
    title: '等不及了',
    description: '第一次催菜',
    emoji: '⏰',
    category: 'interaction',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'first_time',
    evaluatorConfig: { model: 'orderMessage', scopeBy: 'senderUserId', filters: { type: 'rush' } },
    hidden: false,
    progressTarget: null,
    sortOrder: 920,
  },
  {
    key: 'msg_50_sent',
    title: '聊天达人',
    description: '累计发送 50 条消息',
    emoji: '💬',
    category: 'interaction',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'orderMessage',
      scopeBy: 'senderUserId',
      filters: { type: { not: 'system' } },
      threshold: 50,
    },
    hidden: false,
    progressTarget: 50,
    sortOrder: 930,
  },
  {
    key: 'msg_200_sent',
    title: '情话绵绵',
    description: '累计发送 200 条消息',
    emoji: '🗨️',
    category: 'interaction',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'orderMessage',
      scopeBy: 'senderUserId',
      filters: { type: { not: 'system' } },
      threshold: 200,
    },
    hidden: false,
    progressTarget: 200,
    sortOrder: 940,
  },
  {
    key: 'msg_kiss_10',
    title: '亲亲收集',
    description: '发送 10 次亲亲表情',
    emoji: '😘',
    category: 'interaction',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'orderMessage',
      scopeBy: 'senderUserId',
      filters: { type: 'emoji', contentEmojiKey: 'kiss' },
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 950,
  },
  {
    key: 'msg_love_10',
    title: '爱心收集',
    description: '发送 10 次爱心表情',
    emoji: '😍',
    category: 'interaction',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'orderMessage',
      scopeBy: 'senderUserId',
      filters: { type: 'emoji', contentEmojiKey: 'love' },
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 960,
  },
  {
    key: 'msg_emoji_all',
    title: '表情大师',
    description: '使用过全部 8 种表情',
    emoji: '🎭',
    category: 'interaction',
    ownerType: 'user',
    triggerType: 'message_sent',
    evaluatorType: 'message_distinct',
    evaluatorConfig: {
      model: 'orderMessage',
      scopeBy: 'senderUserId',
      filters: { type: 'emoji' },
      distinctField: 'content.emojiKey',
      totalCount: 8,
    },
    hidden: false,
    progressTarget: 8,
    sortOrder: 970,
  },

  // ========================================================================
  // F. 家庭时光 (10)
  // ========================================================================
  {
    key: 'family_first_dish',
    title: '第一道菜',
    description: '家庭完成了第一道菜',
    emoji: '🍽️',
    category: 'family',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'familyId',
      threshold: 1,
    },
    hidden: false,
    progressTarget: 1,
    sortOrder: 1100,
  },
  {
    key: 'family_10_dishes',
    title: '家庭十道菜',
    description: '家庭累计完成 10 道',
    emoji: '🎉',
    category: 'family',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'familyId',
      threshold: 10,
    },
    hidden: false,
    progressTarget: 10,
    sortOrder: 1110,
  },
  {
    key: 'family_50_dishes',
    title: '五十道菜',
    description: '家庭累计完成 50 道',
    emoji: '🎊',
    category: 'family',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'familyId',
      threshold: 50,
    },
    hidden: false,
    progressTarget: 50,
    sortOrder: 1120,
  },
  {
    key: 'family_100_dishes',
    title: '百菜宴',
    description: '家庭累计完成 100 道',
    emoji: '💯',
    category: 'family',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'familyId',
      threshold: 100,
    },
    hidden: false,
    progressTarget: 100,
    sortOrder: 1130,
  },
  {
    key: 'family_365_dishes',
    title: '一年三餐',
    description: '家庭累计完成 365 道',
    emoji: '🏆',
    category: 'family',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'familyId',
      threshold: 365,
    },
    hidden: false,
    progressTarget: 365,
    sortOrder: 1140,
  },
  {
    key: 'family_first_day',
    title: '小厨房成立',
    description: '小厨房成立的第一天',
    emoji: '🏠',
    category: 'family',
    ownerType: 'family',
    triggerType: 'family_joined',
    evaluatorType: 'family_age',
    evaluatorConfig: { minDays: 0 },
    hidden: false,
    progressTarget: null,
    sortOrder: 1150,
  },
  {
    key: 'family_week',
    title: '一周纪念',
    description: '小厨房成立一周',
    emoji: '📅',
    category: 'family',
    ownerType: 'family',
    triggerType: 'daily_check',
    evaluatorType: 'family_age',
    evaluatorConfig: { minDays: 7 },
    hidden: false,
    progressTarget: 7,
    sortOrder: 1160,
  },
  {
    key: 'family_month',
    title: '一月纪念',
    description: '小厨房成立一个月',
    emoji: '🗓️',
    category: 'family',
    ownerType: 'family',
    triggerType: 'daily_check',
    evaluatorType: 'family_age',
    evaluatorConfig: { minDays: 30 },
    hidden: false,
    progressTarget: 30,
    sortOrder: 1170,
  },
  {
    key: 'family_100_days',
    title: '百日纪念',
    description: '小厨房成立 100 天',
    emoji: '💝',
    category: 'family',
    ownerType: 'family',
    triggerType: 'daily_check',
    evaluatorType: 'family_age',
    evaluatorConfig: { minDays: 100 },
    hidden: false,
    progressTarget: 100,
    sortOrder: 1180,
  },
  {
    key: 'family_anniversary',
    title: '周年纪念',
    description: '小厨房成立一周年',
    emoji: '💍',
    category: 'family',
    ownerType: 'family',
    triggerType: 'daily_check',
    evaluatorType: 'family_age',
    evaluatorConfig: { minDays: 365 },
    hidden: false,
    progressTarget: 365,
    sortOrder: 1190,
  },

  // ========================================================================
  // G. 隐藏彩蛋 (7)
  // ========================================================================
  {
    key: 'hidden_valentine',
    title: '情人节限定',
    description: '情人节当天完成一道菜',
    emoji: '🌹',
    category: 'hidden',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'special_date',
    evaluatorConfig: { field: 'completedAt', dates: ['02-14'] },
    hidden: true,
    progressTarget: null,
    sortOrder: 1300,
  },
  {
    key: 'hidden_new_year',
    title: '新年第一餐',
    description: '元旦当天完成一道菜',
    emoji: '🧧',
    category: 'hidden',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'special_date',
    evaluatorConfig: { field: 'completedAt', dates: ['01-01'] },
    hidden: true,
    progressTarget: null,
    sortOrder: 1310,
  },
  {
    key: 'hidden_mid_autumn',
    title: '月圆人团圆',
    description: '中秋节当天完成一道菜',
    emoji: '🌕',
    category: 'hidden',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'special_date',
    evaluatorConfig: { field: 'completedAt', dates: ['dynamic_mid_autumn'] },
    hidden: true,
    progressTarget: null,
    sortOrder: 1320,
  },
  {
    key: 'hidden_christmas',
    title: '圣诞大餐',
    description: '圣诞节当天完成一道菜',
    emoji: '🎄',
    category: 'hidden',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'special_date',
    evaluatorConfig: { field: 'completedAt', dates: ['12-25'] },
    hidden: true,
    progressTarget: null,
    sortOrder: 1330,
  },
  {
    key: 'hidden_perfect_day',
    title: '完美一天',
    description: '一天内完成 3 个订单',
    emoji: '🌈',
    category: 'hidden',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'count',
    evaluatorConfig: {
      model: 'order',
      filters: { status: 'completed' },
      scopeBy: 'familyId',
      sameDay: 'completedAt',
      threshold: 3,
    },
    hidden: true,
    progressTarget: null,
    sortOrder: 1340,
  },
  {
    key: 'hidden_take_turns',
    title: '默契搭档',
    description: '双方各做至少 5 道菜',
    emoji: '🤝',
    category: 'hidden',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'both_members',
    evaluatorConfig: { threshold: 5 },
    hidden: true,
    progressTarget: null,
    sortOrder: 1350,
  },
  {
    key: 'hidden_no_rush',
    title: '耐心等待',
    description: '完成 10 单从未催菜',
    emoji: '🧘',
    category: 'hidden',
    ownerType: 'family',
    triggerType: 'order_rated',
    evaluatorType: 'no_action',
    evaluatorConfig: {
      countModel: 'order',
      countScopeBy: 'familyId',
      countFilters: { status: 'completed' },
      countThreshold: 10,
      excludeModel: 'orderMessage',
      excludeFilters: { type: 'rush' },
      excludeScopeBy: 'orderId',
    },
    hidden: true,
    progressTarget: null,
    sortOrder: 1360,
  },
];

async function main() {
  console.log(`🌱 开始播种徽章定义 (${BADGES.length} 个)...\n`);

  let created = 0;
  let skipped = 0;

  for (const badge of BADGES) {
    const result = await prisma.badgeDefinition.upsert({
      where: { key: badge.key },
      update: {
        title: badge.title,
        description: badge.description,
        emoji: badge.emoji,
        category: badge.category,
        ownerType: badge.ownerType,
        triggerType: badge.triggerType,
        evaluatorType: badge.evaluatorType,
        evaluatorConfig: badge.evaluatorConfig as any,
        hidden: badge.hidden,
        progressTarget: badge.progressTarget,
        sortOrder: badge.sortOrder,
      },
      create: {
        key: badge.key,
        title: badge.title,
        description: badge.description,
        emoji: badge.emoji,
        category: badge.category,
        ownerType: badge.ownerType,
        triggerType: badge.triggerType,
        evaluatorType: badge.evaluatorType,
        evaluatorConfig: badge.evaluatorConfig as any,
        hidden: badge.hidden,
        progressTarget: badge.progressTarget,
        sortOrder: badge.sortOrder,
      },
    });
    if (result) {
      // upsert always returns the record; check if created vs updated
      created++;
    }
  }

  console.log(`✅ 徽章定义处理完成: ${BADGES.length} 条`);
  console.log(
    `   分类: chef(${BADGES.filter((b) => b.category === 'chef').length}), customer(${BADGES.filter((b) => b.category === 'customer').length}), recipe(${BADGES.filter((b) => b.category === 'recipe').length}), love(${BADGES.filter((b) => b.category === 'love').length}), interaction(${BADGES.filter((b) => b.category === 'interaction').length}), family(${BADGES.filter((b) => b.category === 'family').length}), hidden(${BADGES.filter((b) => b.category === 'hidden').length})`,
  );
}

main()
  .catch((e) => {
    console.error('❌ 徽章定义播种失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
