import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import type { Prisma } from '@prisma/client';
import { OrderStatus } from '@family-kitchen/shared';
import { PrismaService } from '../../prisma/prisma.service';
import { paginate, type PaginatedResponseDto } from '../../common/pagination.dto';
import { isTerminal } from '../order/order-status';
import type {
  AdminOrderQueryDto,
  AdminOrderSummaryDto,
  FreezeOrderDto,
} from './dto/admin-resource.dto';

export interface UserNameInfo {
  id: string;
  nickname: string;
  avatarUrl: string | null;
  gender: string | null;
}

@Injectable()
export class AdminOrderService {
  constructor(private readonly prisma: PrismaService) {}

  async list(
    query: AdminOrderQueryDto,
  ): Promise<
    PaginatedResponseDto<AdminOrderSummaryDto & { customer: UserNameInfo; chef: UserNameInfo }>
  > {
    const where: Prisma.OrderWhereInput = {};
    if (query.statuses?.length) where.status = { in: query.statuses };
    if (query.familyId) where.familyId = query.familyId;

    const [orders, total] = await this.prisma.$transaction([
      this.prisma.order.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip: query.skip,
        take: query.take,
        include: {
          customer: { select: { id: true, nickname: true, avatarUrl: true, gender: true } },
          chef: { select: { id: true, nickname: true, avatarUrl: true, gender: true } },
        },
      }),
      this.prisma.order.count({ where }),
    ]);

    return paginate(
      orders.map((o) => ({
        id: o.id,
        familyId: o.familyId,
        customerUserId: o.customerUserId,
        chefUserId: o.chefUserId,
        status: o.status,
        totalLovePoints: o.totalLovePoints,
        createdAt: o.createdAt,
        completedAt: o.completedAt,
        customer: o.customer,
        chef: o.chef,
      })),
      total,
      query.page,
      query.pageSize,
    );
  }

  async detail(id: string) {
    const order = await this.prisma.order.findUnique({
      where: { id },
      include: {
        items: { orderBy: { sortOrder: 'asc' } },
        customer: { select: { id: true, nickname: true, avatarUrl: true } },
        chef: { select: { id: true, nickname: true, avatarUrl: true } },
        rating: true,
      },
    });
    if (!order) {
      throw new NotFoundException({ code: 'ORDER_NOT_FOUND', message: '订单不存在' });
    }
    return {
      id: order.id,
      familyId: order.familyId,
      customerUserId: order.customerUserId,
      chefUserId: order.chefUserId,
      customer: order.customer,
      chef: order.chef,
      status: order.status,
      totalLovePoints: order.totalLovePoints,
      expectedServeAt: order.expectedServeAt,
      customerNotes: order.customerNotes,
      rejectReason: order.rejectReason,
      servedAt: order.servedAt,
      servedImageUrls: Array.isArray(order.servedImageUrls)
        ? (order.servedImageUrls as string[])
        : [],
      createdAt: order.createdAt,
      completedAt: order.completedAt,
      items: order.items.map((i) => ({
        id: i.id,
        recipeId: i.recipeId,
        recipeSnapshot: i.recipeSnapshot,
        customNotes: i.customNotes,
      })),
      rating: order.rating
        ? {
            id: order.rating.id,
            stars: order.rating.stars,
            comment: order.rating.comment,
            imageUrls: Array.isArray(order.rating.imageUrls)
              ? (order.rating.imageUrls as string[])
              : [],
            isAutoGenerated: order.rating.isAutoGenerated,
            createdAt: order.rating.createdAt,
          }
        : null,
    };
  }

  /** 管理员视角：查看订单内消息流（不需要参与方权限） */
  async listMessages(orderId: string): Promise<
    Array<{
      id: string;
      senderUserId: string | null;
      senderNickname: string | null;
      type: string;
      content: unknown;
      createdAt: Date;
    }>
  > {
    const exists = await this.prisma.order.findUnique({
      where: { id: orderId },
      select: { id: true },
    });
    if (!exists) {
      throw new NotFoundException({ code: 'ORDER_NOT_FOUND', message: '订单不存在' });
    }
    const messages = await this.prisma.orderMessage.findMany({
      where: { orderId },
      include: { sender: { select: { nickname: true } } },
      orderBy: { createdAt: 'asc' },
      take: 500,
    });
    return messages.map((m) => ({
      id: m.id,
      senderUserId: m.senderUserId,
      senderNickname: m.sender?.nickname ?? null,
      type: m.type,
      content: m.content,
      createdAt: m.createdAt,
    }));
  }

  /** 管理员强制冻结订单：直接置为 cancelled（仅非终态可冻结） */
  async freeze(id: string, dto: FreezeOrderDto): Promise<AdminOrderSummaryDto> {
    const order = await this.prisma.order.findUnique({ where: { id } });
    if (!order) {
      throw new NotFoundException({ code: 'ORDER_NOT_FOUND', message: '订单不存在' });
    }
    if (isTerminal(order.status as OrderStatus)) {
      throw new BadRequestException({
        code: 'ORDER_ALREADY_TERMINAL',
        message: `订单已是终态（${order.status}），无法冻结`,
      });
    }
    const updated = await this.prisma.order.update({
      where: { id },
      data: {
        status: OrderStatus.CANCELLED,
        rejectReason: `[管理员冻结] ${dto.reason}`,
      },
    });
    return {
      id: updated.id,
      familyId: updated.familyId,
      customerUserId: updated.customerUserId,
      chefUserId: updated.chefUserId,
      status: updated.status,
      totalLovePoints: updated.totalLovePoints,
      createdAt: updated.createdAt,
      completedAt: updated.completedAt,
    };
  }
}
