import { http, type PaginatedResponse } from './http';

// ============================================================
// Metrics
// ============================================================

export interface AdminMetrics {
  totalUsers: number;
  totalFamilies: number;
  activeFamiliesLast7d: number;
  todayDau: number;
  weeklyOrders: number;
  doubleActiveRate: number;
  monthlyLovePointVolume: number;
  snapshotAt: string;
}

// ============================================================
// User profile fragments
// ============================================================

export interface UserBrief {
  id: string;
  nickname: string;
  avatarUrl: string | null;
  gender: string | null;
}

// ============================================================
// Family
// ============================================================

export interface AdminFamilySummary {
  id: string;
  name: string;
  status: string;
  memberCount: number;
  orderCount: number;
  createdAt: string;
}

export interface AdminFamilyDetail extends AdminFamilySummary {
  members: Array<{
    userId: string;
    nickname: string;
    avatarUrl: string | null;
    role: string;
    joinedAt: string;
  }>;
  recentOrders: Array<{
    id: string;
    status: string;
    createdAt: string;
  }>;
}

export interface AdminFamilyLedgerLog {
  id: string;
  userId: string;
  userNickname: string;
  changeAmount: number;
  balanceAfter: number;
  changeType: string;
  sourceOrderId: string | null;
  description: string | null;
  isReversed: boolean;
  createdAt: string;
}

export interface AdminFamilyRecipe {
  id: string;
  name: string;
  difficulty: number;
  mealTags: string[];
  flavorTags: string[];
  isDeleted: boolean;
  orderCount: number;
  avgRating: number | null;
  updatedAt: string;
}

export interface AdminAchievement {
  id: string;
  ownerType: string;
  ownerId: string;
  badgeKey: string;
  sourceOrderId: string | null;
  metadata: Record<string, unknown>;
  unlockedAt: string;
}

export interface FamilyQueryParams {
  page?: number;
  pageSize?: number;
  search?: string;
  statuses?: string[];
}

// ============================================================
// User
// ============================================================

export interface AdminUserSummary {
  id: string;
  nickname: string;
  avatarUrl: string | null;
  gender: string | null;
  currentFamilyId: string | null;
  orderCount: number;
  createdAt: string;
}

export interface AdminUserDetail extends AdminUserSummary {
  phone: string | null;
  signature: string | null;
  lovePointBalance: number;
  achievementCount: number;
  deletedAt: string | null;
}

export interface AdminUserLovePointLog {
  id: string;
  familyId: string;
  changeAmount: number;
  balanceAfter: number;
  changeType: string;
  sourceOrderId: string | null;
  description: string | null;
  isReversed: boolean;
  createdAt: string;
}

export interface UserQueryParams {
  page?: number;
  pageSize?: number;
  search?: string;
}

// ============================================================
// Order
// ============================================================

export interface AdminOrderSummary {
  id: string;
  familyId: string;
  customerUserId: string;
  chefUserId: string;
  status: string;
  totalLovePoints: number;
  createdAt: string;
  completedAt: string | null;
  customer?: UserBrief;
  chef?: UserBrief;
  roleInOrder?: 'customer' | 'chef';
}

export interface AdminOrderItem {
  id: string;
  recipeId: string | null;
  recipeSnapshot: Record<string, unknown>;
  customNotes: string | null;
}

export interface AdminOrderRating {
  id: string;
  stars: number;
  comment: string | null;
  imageUrls: string[];
  isAutoGenerated: boolean;
  createdAt: string;
}

export interface AdminOrderDetail extends AdminOrderSummary {
  expectedServeAt: string | null;
  customerNotes: string | null;
  rejectReason: string | null;
  servedAt: string | null;
  servedImageUrls: string[];
  items: AdminOrderItem[];
  rating: AdminOrderRating | null;
}

export interface AdminOrderMessage {
  id: string;
  senderUserId: string | null;
  senderNickname: string | null;
  type: string;
  content: Record<string, unknown>;
  createdAt: string;
}

export interface OrderQueryParams {
  page?: number;
  pageSize?: number;
  statuses?: string[];
  familyId?: string;
}

// ============================================================
// Feedback
// ============================================================

export interface AdminFeedback {
  id: string;
  userId: string | null;
  content: string;
  contact: string | null;
  status: string;
  appVersion: string | null;
  platform: string | null;
  createdAt: string;
}

export interface FeedbackQueryParams {
  page?: number;
  pageSize?: number;
  statuses?: string[];
}

// ============================================================
// Analytics
// ============================================================

export interface AnalyticsDailyCount {
  date: string;
  count: number;
}

export interface AnalyticsStatusCount {
  status: string;
  count: number;
}

export interface AnalyticsStarsCount {
  stars: number;
  count: number;
}

export interface AnalyticsMonthFlow {
  month: string;
  flow: number;
}

export interface AnalyticsTopRecipe {
  name: string;
  orderCount: number;
}

export interface AnalyticsData {
  dailyOrders: AnalyticsDailyCount[];
  orderStatusDistribution: AnalyticsStatusCount[];
  ratingDistribution: AnalyticsStarsCount[];
  dailyActiveUsers: AnalyticsDailyCount[];
  monthlyLovePoints: AnalyticsMonthFlow[];
  topRecipes: AnalyticsTopRecipe[];
}

// ============================================================
// Pagination helper
// ============================================================

export interface PageParams {
  page?: number;
  pageSize?: number;
}

function arrayParam(value: string[] | undefined): string | undefined {
  return value && value.length > 0 ? value.join(',') : undefined;
}

// ============================================================
// API
// ============================================================

export const adminApi = {
  metrics(): Promise<AdminMetrics> {
    return http.get('/admin/metrics');
  },

  // Families
  listFamilies(params: FamilyQueryParams = {}): Promise<PaginatedResponse<AdminFamilySummary>> {
    return http.get('/admin/families', {
      params: { ...params, statuses: arrayParam(params.statuses) },
    });
  },
  getFamily(id: string): Promise<AdminFamilyDetail> {
    return http.get(`/admin/families/${id}`);
  },
  getFamilyLedger(
    id: string,
    params: PageParams = {},
  ): Promise<PaginatedResponse<AdminFamilyLedgerLog>> {
    return http.get(`/admin/families/${id}/love-point-ledger`, { params });
  },
  getFamilyRecipes(
    id: string,
    params: PageParams = {},
  ): Promise<PaginatedResponse<AdminFamilyRecipe>> {
    return http.get(`/admin/families/${id}/recipes`, { params });
  },
  getFamilyAchievements(id: string): Promise<AdminAchievement[]> {
    return http.get(`/admin/families/${id}/achievements`);
  },

  // Users
  listUsers(params: UserQueryParams = {}): Promise<PaginatedResponse<AdminUserSummary>> {
    return http.get('/admin/users', { params });
  },
  getUser(id: string): Promise<AdminUserDetail> {
    return http.get(`/admin/users/${id}`);
  },
  getUserLovePointLogs(
    id: string,
    params: PageParams = {},
  ): Promise<PaginatedResponse<AdminUserLovePointLog>> {
    return http.get(`/admin/users/${id}/love-point-logs`, { params });
  },
  getUserAchievements(id: string): Promise<AdminAchievement[]> {
    return http.get(`/admin/users/${id}/achievements`);
  },
  getUserOrders(
    id: string,
    params: PageParams = {},
  ): Promise<PaginatedResponse<AdminOrderSummary>> {
    return http.get(`/admin/users/${id}/orders`, { params });
  },

  // Orders
  listOrders(params: OrderQueryParams = {}): Promise<PaginatedResponse<AdminOrderSummary>> {
    return http.get('/admin/orders', {
      params: { ...params, statuses: arrayParam(params.statuses) },
    });
  },
  getOrder(id: string): Promise<AdminOrderDetail> {
    return http.get(`/admin/orders/${id}`);
  },
  getOrderMessages(id: string): Promise<AdminOrderMessage[]> {
    return http.get(`/admin/orders/${id}/messages`);
  },
  freezeOrder(id: string, reason: string): Promise<AdminOrderSummary> {
    return http.post(`/admin/orders/${id}/freeze`, { reason });
  },

  // Feedback
  listFeedback(params: FeedbackQueryParams = {}): Promise<PaginatedResponse<AdminFeedback>> {
    return http.get('/admin/feedback', {
      params: { ...params, statuses: arrayParam(params.statuses) },
    });
  },
  updateFeedbackStatus(id: string, status: string): Promise<AdminFeedback> {
    return http.patch(`/admin/feedback/${id}`, { status });
  },

  // Health
  healthDb(): Promise<{ status: string; latencyMs?: number }> {
    return http.get('/health/db');
  },

  // Analytics
  analytics(): Promise<AnalyticsData> {
    return http.get('/admin/analytics');
  },
};
