<template>
  <view v-if="order" class="page">
    <!-- Status hero -->
    <view class="status-hero">
      <view class="status-hero-decor" />
      <view class="status-hero-inner">
        <view class="status-left">
          <text class="status-text">{{ statusLabel }}</text>
          <view class="role-badge">
            <text>{{ myRoleLabel }}</text>
          </view>
        </view>
        <view v-if="order.expectedServeAt" class="status-time">
          <wd-icon name="clock" size="22rpx" color="rgba(255,255,255,0.7)" />
          <text>{{ formatTimeShort(order.expectedServeAt) }}</text>
        </view>
      </view>
    </view>

    <!-- Items card -->
    <view class="card fade-up" style="margin-top: -24rpx; position: relative; z-index: 2">
      <view class="card-header">
        <view class="card-icon card-icon--amber">
          <wd-icon name="goods" size="28rpx" color="#D4A55A" />
        </view>
        <text class="card-label">点的菜</text>
        <text class="card-count">{{ order.items.length }} 道</text>
      </view>
      <view v-for="item in order.items" :key="item.id" class="item-row">
        <text class="item-name">{{ getName(item) }}</text>
        <text v-if="item.customNotes" class="item-notes">{{ item.customNotes }}</text>
      </view>
      <view v-if="order.customerNotes" class="overall-notes">
        <text class="notes-label">整体备注</text>
        <text class="notes-text">{{ order.customerNotes }}</text>
      </view>
    </view>

    <!-- Served images -->
    <view
      v-if="order.servedImageUrls && order.servedImageUrls.length"
      class="card fade-up fade-up--1"
    >
      <view class="card-header">
        <view class="card-icon card-icon--sage">
          <wd-icon name="camera" size="28rpx" color="#6B9E78" />
        </view>
        <text class="card-label">上菜啦</text>
      </view>
      <view class="images">
        <image
          v-for="url in order.servedImageUrls"
          :key="url"
          class="served-img"
          :src="url"
          mode="aspectFill"
          @click="previewImages(order.servedImageUrls, url)"
        />
      </view>
    </view>

    <!-- Rating (if exists) -->
    <view v-if="order.rating" class="card fade-up fade-up--1">
      <view class="card-header">
        <view class="card-icon card-icon--rose">
          <wd-icon name="star" size="28rpx" color="#E07A5F" />
        </view>
        <text class="card-label">评价</text>
        <text v-if="order.rating.isAutoGenerated" class="auto-tag">自动</text>
      </view>
      <view class="rating-row">
        <wd-rate
          :model-value="order.rating.stars"
          :max="5"
          size="36rpx"
          color="#E07A5F"
          void-color="#D5CEC8"
          readonly
        />
      </view>
      <text v-if="order.rating.comment" class="comment">{{ order.rating.comment }}</text>
    </view>

    <!-- Chat entry -->
    <view class="card fade-up fade-up--2" @click="goChat">
      <view class="chat-entry">
        <view class="chat-entry-left">
          <view class="card-icon card-icon--slate">
            <wd-icon name="chat" size="28rpx" color="#6B8FA8" />
          </view>
          <text class="card-label">沟通</text>
        </view>
        <wd-icon name="arrow-right" size="28rpx" color="#D5CEC8" />
      </view>
    </view>

    <!-- Actions -->
    <view v-if="myRole === 'chef' && hasChefActions" class="actions-section fade-up fade-up--3">
      <view v-if="canAccept" class="action-btn action-btn--primary" @click="handleAccept">
        <wd-icon name="check" size="28rpx" color="#fff" custom-style="margin-right:6rpx" />
        <text>接单</text>
      </view>
      <view v-if="canReject" class="action-btn action-btn--danger" @click="handleReject">
        <text>拒绝</text>
      </view>
      <view v-if="canPrepping" class="action-btn action-btn--primary" @click="handlePrepping">
        <wd-icon name="list" size="28rpx" color="#fff" custom-style="margin-right:6rpx" />
        <text>开始备菜</text>
      </view>
      <view v-if="canCooking" class="action-btn action-btn--primary" @click="handleCooking">
        <wd-icon name="add" size="28rpx" color="#fff" custom-style="margin-right:6rpx" />
        <text>开始烹饪</text>
      </view>
      <view v-if="canServe" class="action-btn action-btn--primary" @click="handleServe">
        <wd-icon name="camera" size="28rpx" color="#fff" custom-style="margin-right:6rpx" />
        <text>上菜（拍照）</text>
      </view>
    </view>

    <view v-if="myRole === 'customer' && canRate" class="actions-section fade-up fade-up--3">
      <view class="action-btn action-btn--primary" @click="rateDialog = true">
        <wd-icon name="star" size="28rpx" color="#fff" custom-style="margin-right:6rpx" />
        <text>写评价</text>
      </view>
    </view>

    <view v-if="isTerminal" class="actions-section fade-up fade-up--3">
      <view class="action-btn action-btn--primary" @click="handleReorder">
        <wd-icon name="refresh" size="28rpx" color="#fff" custom-style="margin-right:6rpx" />
        <text>再来一单</text>
      </view>
    </view>

    <view v-if="canCancel" class="actions-section fade-up fade-up--3">
      <view class="action-btn action-btn--danger" @click="handleCancel">
        <text>取消订单</text>
      </view>
    </view>

    <!-- Bottom spacer -->
    <view class="bottom-spacer" />

    <!-- Rate dialog -->
    <view v-if="rateDialog" class="overlay" @click="rateDialog = false">
      <view class="dialog" @click.stop>
        <text class="dialog-title">给这一顿打分</text>
        <view class="rate-stars">
          <text
            v-for="i in 5"
            :key="i"
            class="big-star"
            :class="{ on: i <= rateForm.stars }"
            @click="rateForm.stars = i"
          >
            ★
          </text>
        </view>
        <textarea
          v-model="rateForm.comment"
          class="dialog-input"
          placeholder="说点什么……（选填）"
          maxlength="500"
        />
        <view class="dialog-actions">
          <text class="dialog-btn" @click="rateDialog = false">取消</text>
          <text class="dialog-btn dialog-btn--primary" @click="handleRate">提交</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script>
import { useAuthStore } from '@/stores/auth.js';
import { useActiveOrderStore } from '@/stores/active-order.js';
import { orderApi } from '@/api/order.js';
import { chooseAndUploadImages } from '@/api/storage.js';
import { ORDER_STATUS_COLOR, ORDER_STATUS_LABEL, formatTimeShort } from '@/utils/labels.js';

const TERMINAL = ['completed', 'rejected', 'cancelled'];

export default {
  data() {
    return {
      id: null,
      order: null,
      rateDialog: false,
      rateForm: { stars: 5, comment: '' },
    };
  },
  computed: {
    myUserId() {
      return useAuthStore().user?.id;
    },
    myRole() {
      return this.order?.myRole;
    },
    myRoleLabel() {
      if (this.myRole === 'customer') {
        return `点了 ${this.order.chefNickname || 'TA'} 的菜`;
      }
      return `${this.order.customerNickname || 'TA'} 点的菜`;
    },
    statusLabel() {
      return ORDER_STATUS_LABEL[this.order?.status] || '';
    },
    statusColor() {
      return ORDER_STATUS_COLOR[this.order?.status] || '#8E8580';
    },
    isTerminal() {
      return this.order ? TERMINAL.includes(this.order.status) : false;
    },
    canAccept() {
      return this.order?.status === 'pending';
    },
    canReject() {
      return this.order?.status === 'pending';
    },
    canPrepping() {
      return this.order?.status === 'accepted';
    },
    canCooking() {
      return this.order?.status === 'prepping';
    },
    canServe() {
      return this.order?.status === 'cooking';
    },
    canCancel() {
      return ['pending', 'accepted', 'prepping', 'cooking'].includes(this.order?.status);
    },
    canRate() {
      return this.order?.status === 'served';
    },
    hasChefActions() {
      return (
        this.canAccept || this.canReject || this.canPrepping || this.canCooking || this.canServe
      );
    },
  },
  onLoad(query) {
    this.id = query.id;
    this.load();
  },
  onShow() {
    if (this.id) this.load();
  },
  methods: {
    formatTimeShort,
    getName(item) {
      return item.recipeSnapshot?.name || '未命名';
    },
    previewImages(urls, current) {
      uni.previewImage({ urls, current });
    },
    goChat() {
      uni.navigateTo({ url: `/pages/order/chat?id=${this.id}` });
    },

    async load() {
      try {
        this.order = await orderApi.get(this.id);
      } catch {
        // ignore
      }
    },

    async refreshAfterAction() {
      await this.load();
      useActiveOrderStore().refresh();
    },

    async handleAccept() {
      await orderApi.accept(this.id);
      await this.refreshAfterAction();
    },
    async handleReject() {
      const res = await new Promise((resolve) => {
        uni.showModal({
          title: '拒绝订单',
          editable: true,
          placeholderText: '原因（选填）',
          success: (r) => resolve(r),
        });
      });
      if (!res.confirm) return;
      await orderApi.reject(this.id, res.content || undefined);
      await this.refreshAfterAction();
    },
    async handlePrepping() {
      await orderApi.setPrepping(this.id);
      await this.refreshAfterAction();
    },
    async handleCooking() {
      await orderApi.setCooking(this.id);
      await this.refreshAfterAction();
    },
    async handleServe() {
      let uploaded;
      try {
        uploaded = await chooseAndUploadImages({
          count: 3,
          category: 'order-served',
        });
      } catch (err) {
        // 用户主动取消选图时 errMsg 包 "cancel"
        const msg = err?.errMsg || err?.message || '';
        if (!msg.includes('cancel')) {
          uni.showToast({ title: '选图失败，请检查权限', icon: 'none' });
        }
        return;
      }
      try {
        const urls = uploaded.map((u) => u.url);
        if (!urls.length) return;
        await orderApi.serve(this.id, urls);
        await this.refreshAfterAction();
      } catch {
        // 错误已由 http 层 toast
      }
    },
    async handleCancel() {
      const res = await new Promise((resolve) => {
        uni.showModal({
          title: '取消订单',
          content: '确定要取消吗？',
          confirmText: '取消订单',
          confirmColor: '#C75B5B',
          editable: true,
          placeholderText: '原因（选填）',
          success: (r) => resolve(r),
        });
      });
      if (!res.confirm) return;
      await orderApi.cancel(this.id, res.content || undefined);
      await this.refreshAfterAction();
    },

    handleReorder() {
      const recipeIds = (this.order.items || [])
        .map((item) => item.recipeSnapshot?.id || item.recipeId)
        .filter(Boolean)
        .join(',');
      const chefUserId = this.order.chefUserId || '';
      uni.navigateTo({
        url: `/pages/order/create?chefUserId=${chefUserId}&recipeIds=${recipeIds}`,
      });
    },

    async handleRate() {
      try {
        await orderApi.rate(this.id, {
          stars: this.rateForm.stars,
          comment: this.rateForm.comment || undefined,
        });
        this.rateDialog = false;
        uni.showToast({ title: '已评价', icon: 'success' });
        await this.refreshAfterAction();
      } catch {
        // ignore
      }
    },
  },
};
</script>

<style lang="scss" scoped>
.page {
  min-height: 100vh;
  background: $fk-bg-page;
  padding-bottom: env(safe-area-inset-bottom);
}

/* ── Status hero ────────────────────────────────────────── */
.status-hero {
  position: relative;
  background: linear-gradient(160deg, #e07a5f 0%, #ee9a86 50%, #f0a08c 100%);
  padding: 48rpx 32rpx 64rpx;
  overflow: hidden;
}

.status-hero-decor {
  position: absolute;
  width: 260rpx;
  height: 260rpx;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.06);
  top: -60rpx;
  right: -40rpx;
}

.status-hero-inner {
  position: relative;
  z-index: 1;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.status-left {
  display: flex;
  align-items: center;
  gap: 16rpx;
}

.status-text {
  font-size: 38rpx;
  font-weight: 700;
  color: #fff;
  letter-spacing: 1rpx;
}

.role-badge {
  padding: 8rpx 24rpx;
  border-radius: 999rpx;
  background: rgba(255, 255, 255, 0.2);
  font-size: 24rpx;
  color: #fff;
  font-weight: 500;
}

.status-time {
  display: flex;
  align-items: center;
  gap: 6rpx;
  font-size: 24rpx;
  color: rgba(255, 255, 255, 0.75);
}

/* ── Cards ──────────────────────────────────────────────── */
.card {
  background: #fff;
  margin: 20rpx 28rpx 0;
  border-radius: 24rpx;
  padding: 28rpx;
  box-shadow:
    0 2rpx 8rpx rgba(142, 133, 128, 0.05),
    0 6rpx 24rpx rgba(142, 133, 128, 0.03);
}

.card-header {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-bottom: 20rpx;
}

.card-icon {
  width: 48rpx;
  height: 48rpx;
  border-radius: 14rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.card-icon--amber {
  background: rgba(212, 165, 90, 0.1);
}
.card-icon--sage {
  background: rgba(107, 158, 120, 0.1);
}
.card-icon--rose {
  background: rgba(224, 122, 95, 0.1);
}
.card-icon--slate {
  background: rgba(107, 143, 168, 0.1);
}

.card-label {
  font-size: 28rpx;
  font-weight: 600;
  color: $fk-text;
}

.card-count {
  margin-left: auto;
  font-size: 24rpx;
  color: $fk-text-muted;
}

/* ── Items ──────────────────────────────────────────────── */
.item-row {
  padding: 16rpx 0;
  border-bottom: 1rpx solid $fk-border-light;
}
.item-row:last-child {
  border-bottom: none;
}

.item-name {
  font-size: 28rpx;
  font-weight: 500;
  color: $fk-text;
}

.item-notes {
  font-size: 24rpx;
  color: $fk-primary;
  margin-top: 6rpx;
}

.overall-notes {
  margin-top: 16rpx;
  padding-top: 16rpx;
  border-top: 1rpx solid $fk-border-light;
}

.notes-label {
  font-size: 24rpx;
  color: $fk-text-muted;
  display: block;
  margin-bottom: 6rpx;
}

.notes-text {
  font-size: 26rpx;
  color: $fk-text-secondary;
  line-height: 1.6;
}

/* ── Served images ──────────────────────────────────────── */
.images {
  display: flex;
  flex-wrap: wrap;
  gap: 16rpx;
}

.served-img {
  width: 200rpx;
  height: 200rpx;
  border-radius: 20rpx;
}

/* ── Rating ─────────────────────────────────────────────── */
.rating-row {
  display: flex;
  align-items: center;
  gap: 8rpx;
}

.auto-tag {
  margin-left: auto;
  font-size: 22rpx;
  color: $fk-text-muted;
  background: $fk-bg-page;
  padding: 4rpx 16rpx;
  border-radius: 999rpx;
}

.comment {
  display: block;
  margin-top: 12rpx;
  font-size: 28rpx;
  color: $fk-text-secondary;
  line-height: 1.6;
}

/* ── Chat entry ─────────────────────────────────────────── */
.chat-entry {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.chat-entry-left {
  display: flex;
  align-items: center;
  gap: 12rpx;
}

/* ── Actions ────────────────────────────────────────────── */
.actions-section {
  margin: 20rpx 28rpx 0;
  display: flex;
  flex-wrap: wrap;
  gap: 16rpx;
}

.action-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 22rpx 0;
  border-radius: 999rpx;
  font-size: 28rpx;
  font-weight: 500;
  flex: 1;
  min-width: 240rpx;
}

.action-btn--primary {
  background: $fk-primary;
  color: #fff;
  box-shadow: 0 6rpx 20rpx rgba(224, 122, 95, 0.25);
}

.action-btn--danger {
  background: #fff;
  color: $fk-error;
  border: 2rpx solid $fk-error;
}

/* ── Bottom spacer ──────────────────────────────────────── */
.bottom-spacer {
  height: 40rpx;
}

/* ── Rate dialog ────────────────────────────────────────── */
.overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.45);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 99;
}

.dialog {
  width: 600rpx;
  background: #fff;
  border-radius: 28rpx;
  padding: 36rpx;
}

.dialog-title {
  font-weight: 700;
  font-size: 34rpx;
  text-align: center;
  color: $fk-text;
  margin-bottom: 28rpx;
}

.rate-stars {
  display: flex;
  justify-content: center;
  gap: 16rpx;
  margin-bottom: 28rpx;
}

.big-star {
  font-size: 64rpx;
  color: $fk-star-off;
}

.big-star.on {
  color: $fk-primary;
}

.dialog-input {
  width: 100%;
  min-height: 160rpx;
  background: $fk-bg-page;
  border: none;
  border-radius: 16rpx;
  padding: 20rpx 24rpx;
  font-size: 28rpx;
  box-sizing: border-box;
  margin-bottom: 28rpx;
}

.dialog-actions {
  display: flex;
  justify-content: flex-end;
  gap: 40rpx;
}

.dialog-btn {
  font-size: 28rpx;
  color: $fk-text-muted;
}

.dialog-btn--primary {
  color: $fk-primary;
  font-weight: 600;
}

/* ── Animations ─────────────────────────────────────────── */
@keyframes fadeUp {
  from {
    opacity: 0;
    transform: translateY(20rpx);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.fade-up {
  animation: fadeUp 0.4s ease-out both;
}

.fade-up--1 {
  animation-delay: 0.06s;
}
.fade-up--2 {
  animation-delay: 0.12s;
}
.fade-up--3 {
  animation-delay: 0.18s;
}
</style>
