import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import type { Prisma } from '@prisma/client';
import { LovePointChangeType, OrderStatus } from '@family-kitchen/shared';
import { PrismaService } from '../../prisma/prisma.service';
import { requireFamilyId } from '../../common/family-context';
import { LovePointService } from '../love-point/love-point.service';
import { TimelineService } from '../timeline/timeline.service';
import { AchievementService } from '../achievement/achievement.service';
import { NotificationService } from '../notification/notification.service';
import { BusinessConfigService } from '../business-config/business-config.service';
import { AchievementOwnerType } from '@family-kitchen/shared';
import { assertTransition } from './order-status';
import type {
  CreateRatingDto,
  RatingDto,
  RatingSettlementResultDto,
} from './dto/create-rating.dto';

@Injectable()
export class RatingService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly lovePoint: LovePointService,
    private readonly timeline: TimelineService,
    private readonly achievement: AchievementService,
    private readonly notification: NotificationService,
    private readonly bizConfig: BusinessConfigService,
  ) {}

  /**
   * 食客评价订单。
   * 在单次事务里完成：
   *   1. Rating 写入
   *   2. order 状态机：served → rated → completed（MVP 直接一气到 completed）
   *   3. 计算厨师爱心币（基础 + 难度 + 评分加成 + 5 星额外）
   *   4. 写 LovePointLog（厨师维度，家庭账本同时落）
   *   5. 更新 order.totalLovePoints
   *   6. 更新涉及菜谱的 avgRating + orderCount（冗余字段）
   *   7. 生成 TimelineEntry
   */
  async create(
    userId: string,
    orderId: string,
    dto: CreateRatingDto,
  ): Promise<RatingSettlementResultDto> {
    const familyId = await requireFamilyId(this.prisma, userId);

    const order = await this.prisma.order.findUnique({
      where: { id: orderId },
      include: { items: true, rating: true },
    });
    if (!order) {
      throw new NotFoundException({ code: 'ORDER_NOT_FOUND', message: '订单不存在' });
    }
    if (order.familyId !== familyId) {
      throw new ForbiddenException({
        code: 'ORDER_NOT_IN_YOUR_FAMILY',
        message: '不能评价其他小厨房的订单',
      });
    }
    if (order.customerUserId !== userId) {
      throw new ForbiddenException({
        code: 'RATING_FOR_CUSTOMER_ONLY',
        message: '只有食客可以评价',
      });
    }
    if (order.rating) {
      throw new ConflictException({
        code: 'ALREADY_RATED',
        message: '该订单已评价过',
      });
    }
    if (order.status !== OrderStatus.SERVED) {
      throw new BadRequestException({
        code: 'ORDER_NOT_SERVED',
        message: '订单还未上菜，不能评价',
      });
    }

    // 校验状态机（served → rated；后面再一步到 completed）
    assertTransition(order.status as OrderStatus, OrderStatus.RATED);

    // 计算厨师奖励
    const lovePoints = this.calculateChefReward(order.items, dto.stars);

    const result = await this.prisma.$transaction(async (tx) => {
      // 1. 写 Rating
      const rating = await tx.rating.create({
        data: {
          orderId: order.id,
          raterUserId: userId,
          stars: dto.stars,
          comment: dto.comment ?? null,
          imageUrls: (dto.imageUrls ?? []) as unknown as Prisma.InputJsonValue,
          isAutoGenerated: false,
        },
      });

      // 2. order: served → rated → completed（单次写入）
      const now = new Date();
      await tx.order.update({
        where: { id: order.id },
        data: {
          status: OrderStatus.COMPLETED,
          totalLovePoints: lovePoints,
          completedAt: now,
        },
      });

      // 3+4. 写 LovePointLog（厨师视角；TIP 流水之前已落，此处只是做菜奖励）
      await this.lovePoint.addLog(
        {
          userId: order.chefUserId,
          familyId: order.familyId,
          changeAmount: lovePoints,
          changeType: LovePointChangeType.COOK_REWARD,
          sourceOrderId: order.id,
          description: `做菜奖励（${dto.stars} 星）`,
        },
        tx as never,
      );

      // 6. 菜谱冗余字段更新（按本订单菜品）
      await this.bumpRecipeAggregates(tx, order.items, dto.stars);

      // 7. TimelineEntry
      const servedImages = Array.isArray(order.servedImageUrls)
        ? (order.servedImageUrls as string[])
        : [];
      const entry = await this.timeline.createFromOrder(
        {
          familyId: order.familyId,
          orderId: order.id,
          occurredAt: order.servedAt ?? now,
          imageUrls: servedImages,
          customerUserId: order.customerUserId,
          chefUserId: order.chefUserId,
          customerComment: dto.comment ?? null,
          chefComment: null,
        },
        tx as never,
      );

      return {
        rating,
        timelineEntry: entry,
      };
    });

    // 事务外触发：成就评估（失败不影响主流程）+ 微信订阅消息推送
    void this.triggerSideEffects({
      order: {
        id: order.id,
        familyId: order.familyId,
        customerUserId: order.customerUserId,
        chefUserId: order.chefUserId,
        servedAt: order.servedAt,
        completedAt: new Date(),
        items: order.items,
      },
      stars: dto.stars,
      comment: dto.comment,
      lovePointsAwarded: lovePoints,
    });

    return {
      rating: this.toRatingDto(result.rating),
      lovePointsAwarded: lovePoints,
      orderStatus: OrderStatus.COMPLETED,
      timelineEntryId: result.timelineEntry.id,
    };
  }

  /**
   * 事务外的副作用：跑成就 + 发通知。
   * 这两件事失败都不应该回滚业务事务，所以放外面 fire-and-forget。
   */
  private async triggerSideEffects(input: {
    order: {
      id: string;
      familyId: string;
      customerUserId: string;
      chefUserId: string;
      servedAt?: Date | null;
      completedAt?: Date | null;
      items?: Array<{ recipeId: string | null; recipeSnapshot: unknown }>;
    };
    stars: number;
    comment?: string | null;
    lovePointsAwarded?: number;
  }): Promise<void> {
    try {
      const unlocked = await this.achievement.evaluateAfterRating({
        prisma: this.prisma,
        order: input.order,
        stars: input.stars,
        comment: input.comment,
      });
      for (const a of unlocked) {
        // 从 DB 查询徽章定义
        const def = await this.prisma.badgeDefinition.findUnique({
          where: { key: a.badgeKey },
        });
        if (!def) continue;
        // 个人徽章发给厨师，家庭徽章双方都发
        const recipients =
          a.ownerType === AchievementOwnerType.FAMILY
            ? [input.order.customerUserId, input.order.chefUserId]
            : [a.ownerId];
        for (const userId of recipients) {
          const user = await this.prisma.user.findUnique({
            where: { id: userId },
          });
          if (!user?.wxOpenid) continue;
          await this.notification.sendAchievementUnlocked({
            userId,
            userOpenid: user.wxOpenid,
            badgeTitle: def.title,
            badgeDescription: def.description,
          });
        }
      }

      // 触发 love_point_earned 成就评估（厨师获得了爱心值）
      if (input.lovePointsAwarded && input.lovePointsAwarded > 0) {
        await this.achievement.evaluate('love_point_earned', {
          prisma: this.prisma,
          userId: input.order.chefUserId,
          familyId: input.order.familyId,
          triggerType: 'love_point_earned',
          order: input.order,
          amount: input.lovePointsAwarded,
          changeType: 'cook_reward',
        });
      }
    } catch {
      // 成就 / 通知失败已在各自服务里 warn，这里再吞一层兜底
    }
  }

  // ============================================================
  // internal
  // ============================================================

  /** 公式：sum(每道菜的 基础 + 难度×系数) + (评分-3)×系数（评分≤3 不扣）+ 5 星额外 */
  private calculateChefReward(items: Array<{ recipeSnapshot: unknown }>, stars: number): number {
    const formula = this.bizConfig.getLovePointFormula();
    let total = 0;
    for (const item of items) {
      const snap = (item.recipeSnapshot ?? {}) as Record<string, unknown>;
      const difficulty = typeof snap.difficulty === 'number' ? (snap.difficulty as number) : 3;
      total += formula.BASE + difficulty * formula.DIFFICULTY_MULTIPLIER;
    }
    if (stars > 3) {
      total += (stars - 3) * formula.RATING_BONUS_MULTIPLIER;
    }
    if (stars === 5) {
      total += formula.FIVE_STAR_EXTRA_BONUS;
    }
    return total;
  }

  /** 重新计算菜谱聚合：orderCount 和 avgRating（按所有未撤销评价） */
  private async bumpRecipeAggregates(
    tx: Prisma.TransactionClient,
    items: Array<{ recipeId: string | null }>,
    stars: number,
  ): Promise<void> {
    for (const item of items) {
      if (!item.recipeId) continue;
      const recipe = await tx.recipe.findUnique({ where: { id: item.recipeId } });
      if (!recipe) continue;
      const newCount = recipe.orderCount + 1;
      const newAvg =
        recipe.avgRating === null
          ? stars
          : Math.round(((recipe.avgRating * recipe.orderCount + stars) / newCount) * 100) / 100;
      await tx.recipe.update({
        where: { id: item.recipeId },
        data: { orderCount: newCount, avgRating: newAvg },
      });
    }
  }

  private toRatingDto(rating: {
    id: string;
    orderId: string;
    raterUserId: string;
    stars: number;
    comment: string | null;
    imageUrls: unknown;
    createdAt: Date;
  }): RatingDto {
    return {
      id: rating.id,
      orderId: rating.orderId,
      raterUserId: rating.raterUserId,
      stars: rating.stars,
      comment: rating.comment,
      imageUrls: Array.isArray(rating.imageUrls) ? (rating.imageUrls as string[]) : [],
      createdAt: rating.createdAt,
    };
  }
}
