import { ApiProperty } from '@nestjs/swagger';

export class OrderItemOutputDto {
  @ApiProperty()
  id!: string;

  @ApiProperty({ nullable: true })
  recipeId!: string | null;

  @ApiProperty({ description: '当时下单的菜谱快照' })
  recipeSnapshot!: {
    name: string;
    imageUrls: string[];
    difficulty: number;
  };

  @ApiProperty({ nullable: true })
  customNotes!: string | null;

  @ApiProperty()
  sortOrder!: number;
}

export class OrderServedImageInfo {
  @ApiProperty({ type: [String] })
  imageUrls!: string[];

  @ApiProperty({ nullable: true })
  servedAt!: Date | null;
}

export class OrderRatingOutputDto {
  @ApiProperty()
  stars!: number;

  @ApiProperty({ nullable: true })
  comment!: string | null;

  @ApiProperty()
  isAutoGenerated!: boolean;
}

export class OrderDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  familyId!: string;

  @ApiProperty()
  customerUserId!: string;

  @ApiProperty()
  chefUserId!: string;

  @ApiProperty({
    enum: [
      'pending',
      'accepted',
      'prepping',
      'cooking',
      'served',
      'rated',
      'completed',
      'rejected',
      'cancelled',
    ],
  })
  status!: string;

  @ApiProperty({ nullable: true })
  expectedServeAt!: Date | null;

  @ApiProperty({ nullable: true })
  customerNotes!: string | null;

  @ApiProperty({ nullable: true })
  rejectReason!: string | null;

  @ApiProperty({ type: [OrderItemOutputDto] })
  items!: OrderItemOutputDto[];

  @ApiProperty({ type: [String], description: '上菜成品图（仅 served 之后有）' })
  servedImageUrls!: string[];

  @ApiProperty({ nullable: true })
  servedAt!: Date | null;

  @ApiProperty({ nullable: true })
  completedAt!: Date | null;

  @ApiProperty({ description: '本订单累计产生的爱心币' })
  totalLovePoints!: number;

  @ApiProperty({ nullable: true, type: OrderRatingOutputDto })
  rating!: OrderRatingOutputDto | null;

  @ApiProperty()
  createdAt!: Date;

  @ApiProperty()
  updatedAt!: Date;

  @ApiProperty({ description: '当前用户在此订单的角色', enum: ['customer', 'chef'] })
  myRole!: 'customer' | 'chef';

  @ApiProperty({ nullable: true })
  customerNickname!: string | null;

  @ApiProperty({ nullable: true })
  chefNickname!: string | null;

  @ApiProperty({ nullable: true })
  customerAvatarUrl!: string | null;

  @ApiProperty({ nullable: true })
  chefAvatarUrl!: string | null;

  @ApiProperty({ description: '当前用户未读消息数' })
  unreadCount!: number;
}
